# Generated by Django 2.1.1 on 2018-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('sale_place', models.CharField(max_length=200)),
                ('sales', models.IntegerField(default=0)),
                ('sub_date', models.DateTimeField(verbose_name='date submited')),
            ],
        ),
    ]
